## cartridge.properties for cartridge int_flexpay
#Fri Sep 05 2025 11:25:20 GMT-0400 (Eastern Daylight Time)
demandware.cartridges.int_flexpay_sfra5.multipleLanguageStorefront=true
demandware.cartridges.int_flexpay_sfra5.id=int_flexpay_sfra5
