## cartridge.properties for cartridge int_flexpay
#Fri Sep 05 2025 11:25:20 GMT-0400 (Eastern Daylight Time)
demandware.cartridges.int_flexpay.multipleLanguageStorefront=true
demandware.cartridges.int_flexpay.id=int_flexpay
